name: Update Nightly Python Package

on:
  schedule:
    - cron: "0 23 * * *"

jobs:
  push-pypi:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        ref: nightly
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Check for commits within time 
      uses: AlexHolderDeveloper/CommitsWithinTime@v1.1.5
      id: commitswithintime
      with:
        hours: 24

    - name: Get the output from CommitsWithinTime
      run: |
        echo "The 'has-new-commits-within-time' value is ${{ steps.commitswithintime.outputs.has-new-commits-within-time }}"
        echo "The 'number-of-commits-within-time' value is ${{ steps.commitswithintime.outputs.number-of-commits-within-time }}"
        echo "The 'total-commits' value is ${{ steps.commitswithintime.outputs.total-commits }}"

    - name: Install dependencies
      if: steps.commitswithintime.outputs.has-new-commits-within-time
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel twine build

    - name: Setup Nightly Build
      if: steps.commitswithintime.outputs.has-new-commits-within-time
      run: python .github/prepare_nightly.py

    - name: Build a binary wheel and a source tarball
      if: steps.commitswithintime.outputs.has-new-commits-within-time
      run: python -m build --sdist --wheel --outdir dist/ .

    - name: Publish distribution to PyPI
      if: steps.commitswithintime.outputs.has-new-commits-within-time
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API }}
